### ISSUE TITLE
EPIC: Various UI fixes/improvements needed before presentation

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#482]
# Problem
There are various UI/Experience improvements needed in both portrait and landscape mode. Making this a collective issue with all of them we want to fix before a presentation in June.

### Requirements

- [ ] Remove the Beta Banner
- [ ] Stretch goal: add the welcome banner #133 

landscape-mode specific
- [ ] Fix the search bar overlapping the site icon
- [ ] make the search bar in the middle of the top navbar

portrait-mode specific
- [ ] fix the floating footer
- [ ] improve the about us page in mobile view. implemented in #474 
- [ ] improve the hamburger menu. implemented in #57 
- [ ] Improve the selected doctor modal experience. (Add separate ticket here)

**Comment by ermish** [comment]
@theyokohamalife feel free to add any that are missing/more important
