### ISSUE TITLE
FEAT: Epic - Set up Auth for our site

### ISSUE THREAD

**Issue by ermish** [ourjapanlife/findadoc-web#542]
# Epic for Auth work
We want to allow our admins/moderators to login to the moderator dashboard. We also want to make sure someone unauthorized cannot use the moderation dashboard. 

This is work is quite large, so might be broken into separate issues for some parts. This will be the epic (parent ticket with a bunch of smaller tickets needed to complete it). 

### Requirements

- [x] Create a login page #575
- [x] Create an auth store that handles user login, logout, and keeping track of logged in status #575
- [x] Add in redirection and blocking/unblocking the moderator dashboard #575
- [x] Add support to refresh tokens #575
- [x] Integrate auth into all the requests by the client side #574
- [x] Add support for roles #571 #572 
- [x] Add auth checks to API #573 
- [x] Secure API routes to only admin and moderator roles #572
- [x] Add some tests! #570

**Comment by NabbeunNabi** [comment]
No tests still is all I see
